"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

# with open("requirements.txt") as rs: required = rs.read().splitlines()
OPTIONS = {"resources":["prefs", "data", "credentials"]}

setup(
    app=['main.py'],
    name="Report Generator",
    version="1.0",
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
